### ISSUE TITLE
Vettori vs tensori

### ISSUE THREAD

**Issue by edo01** [AMSC22-23/FFT-Carra-Ferrario-Gentile#1]
Come si legge dal titolo della issue, bisogna capire come gestire il caso 1-D e 2-D. I tensori ci permettono di estendere al caso N-D con un costo in termini di performance che non possiamo trascurare. Utilizzare un semplice vettore/matrice per il caso unidimensionale e bidimensionale  può essere una soluzione. 

- Come si rifletterebbe sull'utilizzo da parte del cliente e sulla struttura delle classi?  
- C'è un modo di rendere l'utilizzo di vettori e tensori in modo che sia trasparente al cliente senza che l'utilizzo della libreria diventi eccessivamente complicato?

**Comment by Ferraah** [comment]
Empiric tests on accesses and writes with Tensors compared to Matrixes/Vectors show that the slowdown is minimum, so we will base the library on Tensors for every dimension.
