### ISSUE TITLE
Discordanza tra il rank del solver e il rank della strategy

### ISSUE THREAD

**Issue by edo01** [AMSC22-23/FFT-Carra-Ferrario-Gentile#3]
Al momento è possibile che si verifichi la seguente situazione:

```C++
template<typename DataType>
classe FFT_ONLY_1D:
public FFT_1D<DataType> {
...
}

\\ nel main si crea un solver di rank 3
FFTSolver<double,3> fft_solver(std::make_unique<FFT_ONLY_1D<double>>());

```

Ci sono due modi per gestire questa cosa:
- Riprodurre la gerarchia della strategy anche sul solver. In questo modo l'utente non si crea un FFTSolver<double,3> ma un FFTSolver_3D<double> che accetta solo strategy 3D.
- Usare degli static assert con opportuni codici di errore (un po' meno pulita come soluzione a mio parere).

**Comment by Ferraah** [comment]
The problem has been solved using templates.
